### PR TITLE
Feature/update priority

### PR DESCRIPTION
**Pull request by starcolon**
Add some basic functionalities as follows
- Peeking an item at a specified index.
- Removing an item at a specified index.
- Update an item at a specified index and rearranging its position in the queue.

Re-adjustment of a priority value of a priority queue is commonly-used by some applications (e.g. Dijkstra algorithm). Having this feature out-of-the-box would be very useful.

### CODE REVIEW

**Comment by xgbuils** [comment]
Hi @starcolon 

Why do you want to peek an item at a specified index if you don't know what value are in this index? Think that value at a specified index is not the same that index-th item with more priority,

**Comment by starcolon** [comment]
Hi @xgbuils 

Thank you for your comments. The key function would be `updatePriority` which I want to add a functionality where people can update an item with new priority value or even content value. This is for a case where the index of a certain item is addressed from `.forEach()`. 

`removeAt()` is then added as an auxiliary function for this functionality (simple one). Having an `updatePriority` function which requires an index would be easier to understand than using a filter function to match one (Just an idea).

What do you think?

**Comment by xgbuils** [comment]
Hi @starcolon 

You are right, you could know index using forEach. However, updating priorities might produce weird behaviours. For example, if the priority of item was updated inside forEach, this item could be traversed one more time and one of items of queue could be not traversed.

**Comment by starcolon** [comment]
That's a good point indeed, @xgbuils . At first I thought using index to address which one to update would be a good option since updating only one element at a time will be handy to remove that certain item and re-adding it. 

Maybe having `updatePriority` which takes a boolean function to filter a certain item in the queue to update would be another option to go. e.g.: `updatePriority((n) => n.name=='john', (n) => n.pri++ )`
Do you have a concern or suggestion on this?

**Comment by janogonzalez** [comment]
Closing for lack of activity

**Pull request closed without merging**
